CREATE TABLE TASK_QUEUE (
  ID  INT(255) NOT NULL AUTO_INCREMENT,
  ATTEMPTS INT(255) NOT NULL ,
  CREATE_TIMESTAMP TIMESTAMP(255) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CREATE_USER VARCHAR(255) NOT NULL ,
  REFERENCE_ID VARCHAR(255),
  REFERENCE_TYPE VARCHAR(255),
  OPERATION_NAME VARCHAR(255),
  SYNC_ID VARCHAR(255)  NOT NULL ,
  PROCESS_MESSAGE TEXT,
  REQUEST_MESSAGE JSON NOT NULL ,
  SOURCE VARCHAR(255) NOT NULL ,
  STATUS ENUM ('NEW', 'ONHOLD', 'FAILED', 'WAIT', 'BLOCKED', 'ABORTED', 'COMPLETED', 'WARN', 'STOP') NOT NULL ,
  TARGET VARCHAR(255) NOT NULL ,
  TARGET_URL VARCHAR(255) NOT NULL ,
  TRANSACTION_ID VARCHAR(255),
  UPDATE_TIMESTAMP TIMESTAMP,
  PRIMARY KEY (ID, CREATE_TIMESTAMP), 
  INDEX (REFERENCE_ID,REFERENCE_TYPE,SYNC_ID, SOURCE, TARGET, TRANSACTION_ID, STATUS, OPERATION_NAME))
 	PARTITION BY RANGE( YEAR(CREATE_TIMESTAMP) )
    SUBPARTITION BY HASH(TARGET)
    SUBPARTITIONS 10 (
        PARTITION p0 VALUES LESS THAN (2020),
        PARTITION p1 VALUES LESS THAN (2021),
        PARTITION p2 VALUES LESS THAN (2022),
        PARTITION p3 VALUES LESS THAN (2023),
        PARTITION p4 VALUES LESS THAN (2024),
        PARTITION p5 VALUES LESS THAN (2025),
        PARTITION p6 VALUES LESS THAN MAXVALUE
    );